import Lax808846Proofs.Transfer
import Lax496464Proofs.WHierarchy.Machine.ReadTape
import Lax496464Proofs.WHierarchy.Lemmas.WDToWSat.Output

/-!
# The IMP+ Program of `p-WD_φ ≤ p-WSat(d-CNF)`: Definitions

The program is built from the fixed data `D` of the formula: the parts that depend on it (the fit
test, the powers, the digits, the clauses and their literals) are generated by Lean functions, with
the formula's constants written in as literals. Arrays: `a` (the word), `bo` (block positions), `U`
(the elements), `od` (the digits of the current assignment). All scalars are prefixed `w_`.
-/

namespace Lax496464Proofs.WHierarchy.Lemmas.WDToWSat.ProgDefs

open Lax808846Proofs.Imp Lax808846Proofs.Compile
open Lax496464Proofs.WHierarchy.Lemmas.WDToWSat.Cnf Lax496464Proofs.WHierarchy.Lemmas.WDToWSat.Output

abbrev V (s : String) : Expr := .var s
abbrev bump (s : String) : Com := .assign s (.add (V s) (.lit 1))

/-- A list of commands in sequence. -/
def seqList : List Com → Com
  | [] => .skip
  | c :: cs => .seq c (seqList cs)

/-! ### Reading the header and testing the fit -/

/-- `sp := a[0]; N := a[1 + sp]; k := a[|x| - 1]`. -/
def headCom : Com :=
  .seq (.assign "w_sp" (.get "a" (.lit 0)))
    (.seq (.assign "w_N" (.get "a" (.add (.lit 1) (V "w_sp"))))
      (.assign "w_k" (.get "a" (.sub (V "rt_n") (.lit 1)))))

/-- Test one relation atom `(i, l)`: `i < sp` and `a[1 + i] = l`. -/
def relCheck (p : ℕ × ℕ) : Com :=
  .ite (.lt (.lit p.1) (V "w_sp"))
    (.ite (.eq (.get "a" (.lit (1 + p.1))) (.lit p.2)) .skip (.assign "w_ft" (.lit 0)))
    (.assign "w_ft" (.lit 0))

/-- The fit test, into `w_ft`. -/
def fitCom (D : Data) : Com :=
  .seq (.assign "w_ft" (.lit (if D.sfit then 1 else 0))) (seqList (D.rels.map relCheck))

/-! ### The blocks and the elements -/

/-- One block: record its position, skip it. -/
def boBody : Com :=
  .seq (.store "bo" (V "w_i") (V "w_p"))
    (.seq (.assign "w_p" (.add (.add (V "w_p") (.lit 1))
      (.mul (.get "a" (V "w_p")) (.get "a" (.add (.lit 1) (V "w_i"))))))
      (bump "w_i"))

/-- The loop over the blocks. -/
def boLoop : Com := .seq (.assign "w_i" (.lit 0)) (.while (.lt (V "w_i") (V "w_sp")) boBody)

/-- **The block positions.** -/
def boCom : Com := .seq (.assign "w_p" (.add (.lit 2) (V "w_sp"))) boLoop

/-- `L := min(N, |x| + s·k + r)`. -/
def LCom (D : Data) : Com :=
  .seq (.assign "w_t" (.add (.add (V "rt_n") (.mul (.lit D.s) (V "w_k"))) (.lit D.r)))
    (.ite (.lt (V "w_t") (V "w_N")) (.assign "w_L" (V "w_t")) (.assign "w_L" (V "w_N")))

/-- `U[e] := e`. -/
def fill1Body : Com := .seq (.store "U" (V "w_e") (V "w_e")) (bump "w_e")

/-- The elements `0, …, L-1`. -/
def fill1 : Com := .seq (.assign "w_e" (.lit 0)) (.while (.lt (V "w_e") (V "w_L")) fill1Body)

/-- One step of the membership scan. -/
def memBody : Com :=
  .seq (.ite (.eq (.get "U" (V "w_q")) (V "w_e")) (.assign "w_f" (.lit 1)) .skip) (bump "w_q")

/-- The scan loop. -/
def memLoop : Com := .seq (.assign "w_q" (.lit 0)) (.while (.lt (V "w_q") (V "w_n")) memBody)

/-- `f := [e ∈ U[0..n)]`. -/
def memScan : Com := .seq (.assign "w_f" (.lit 0)) memLoop

/-- Append `e` if new. -/
def pushNew : Com :=
  .seq memScan (.ite (.eq (V "w_f") (.lit 0)) (.seq (.store "U" (V "w_n") (V "w_e")) (bump "w_n")) .skip)

/-- One entry of the word. -/
def fill2Body : Com :=
  .seq (.assign "w_e" (.get "a" (V "w_p")))
    (.seq (.ite (.lt (V "w_e") (V "w_L")) .skip (.ite (.lt (V "w_e") (V "w_N")) pushNew .skip))
      (bump "w_p"))

/-- The other entries of the word below `N`. -/
def fill2 : Com := .seq (.assign "w_p" (.lit 0)) (.while (.lt (V "w_p") (V "rt_n")) fill2Body)

/-- **The elements.** -/
def uCom : Com := .seq fill1 (.seq (.assign "w_n" (V "w_L")) fill2)

/-! ### Powers, digits -/

/-- `e` multiplications by `n`. -/
def powSteps (v : String) : ℕ → Com
  | 0 => .skip
  | e + 1 => .seq (powSteps v e) (.assign v (.mul (V v) (V "w_n")))

/-- `v := n ^ e`. -/
def powCom (v : String) (e : ℕ) : Com := .seq (.assign v (.lit 1)) (powSteps v e)

/-- The digits from position `j` on. -/
def decSteps : ℕ → ℕ → Com
  | _, 0 => .skip
  | j, c + 1 =>
    .seq (.store "od" (.lit j) (.sub (V "w_w") (.mul (.div (V "w_w") (V "w_n")) (V "w_n"))))
      (.seq (.assign "w_w" (.div (V "w_w") (V "w_n"))) (decSteps (j + 1) c))

/-- `od := digits n r z`. -/
def decodeCom (r : ℕ) : Com := .seq (.assign "w_w" (V "w_z")) (decSteps 0 r)

/-! ### Atoms and clauses -/

/-- The element at position `j`, `U[od[j]]`. -/
abbrev elemE (j : ℕ) : Expr := .get "U" (.get "od" (.lit j))

/-- The position of entry `q` of tuple `t` of the block, tuples of length `l`. -/
abbrev posE (l q : ℕ) : Expr := .add (.add (.add (V "w_bs") (.lit 1)) (.mul (V "w_t") (.lit l))) (.lit q)

/-- Compare the tuple with the elements at the positions `js`, from entry `q` on. -/
def matchCom (l : ℕ) : List ℕ → ℕ → Com
  | [], _ => .skip
  | j :: js, q =>
    .seq (.ite (.eq (.get "a" (posE l q)) (elemE j)) .skip (.assign "w_mt" (.lit 0)))
      (matchCom l js (q + 1))

/-- One tuple of the block. -/
def tupBody (js : List ℕ) : Com :=
  .seq (.assign "w_mt" (.lit 1))
    (.seq (matchCom js.length js 0)
      (.seq (.ite (.eq (V "w_mt") (.lit 1)) (.assign "w_f" (.lit 1)) .skip) (bump "w_t")))

/-- The scan of the block. -/
def tupLoop (js : List ℕ) : Com :=
  .seq (.assign "w_t" (.lit 0)) (.while (.lt (V "w_t") (V "w_cnt")) (tupBody js))

/-- `f := [the tuple at js ∈ R_i]`. -/
def relCom (i : ℕ) (js : List ℕ) : Com :=
  .seq (.assign "w_bs" (.get "bo" (.lit i)))
    (.seq (.assign "w_cnt" (.get "a" (V "w_bs")))
      (.seq (.assign "w_f" (.lit 0)) (tupLoop js)))

/-- `f := [the atom holds]`. -/
def atomCom : Atom → Com
  | .rel i js => relCom i js
  | .eq a b => .ite (.eq (elemE a) (elemE b)) (.assign "w_f" (.lit 1)) (.assign "w_f" (.lit 0))
  | .setVar _ => .skip

/-- `1` for `true`. -/
def bv (b : Bool) : ℕ := if b then 1 else 0

/-- A literal without `X`: set `st` if it holds. -/
def nonXCom (l : Lit) : Com :=
  .seq (atomCom l.atom) (.ite (.eq (V "w_f") (.lit (bv l.pos))) (.assign "w_st" (.lit 1)) .skip)

/-- `c := codeOf n (od[js])`. -/
def codeCom : List ℕ → Com
  | [] => .assign "w_c" (.lit 0)
  | j :: js => .seq (codeCom js) (.assign "w_c" (.add (.get "od" (.lit j)) (.mul (V "w_n") (V "w_c"))))

/-- An `X`-literal: write its code. -/
def xLitCom (l : Lit) : Com :=
  .seq (codeCom l.atom.idxs) (.write (.add (.mul (.lit 2) (V "w_c")) (.lit (1 - bv l.pos))))

/-- Write the three entries `2, 0, 1` of `Y₀ ∨ ¬Y₀`. -/
def writeTaut0 : Com := .seq (.write (.lit 2)) (.seq (.write (.lit 0)) (.write (.lit 1)))

/-- **One clause.** -/
def clauseCom (C : List Lit) : Com :=
  .seq (.assign "w_st" (.lit 0))
    (.seq (seqList ((C.filter fun l => !isXLit l).map nonXCom))
      (.ite (.eq (V "w_st") (.lit 1)) writeTaut0
        (.seq (.write (.lit (C.filter isXLit).length)) (seqList ((C.filter isXLit).map xLitCom)))))

/-- One assignment: its digits, its clauses. -/
def zBody (D : Data) : Com :=
  .seq (decodeCom D.r) (.seq (seqList (D.cnf.map clauseCom)) (bump "w_z"))

/-- The loop over the assignments. -/
def zLoop (D : Data) : Com :=
  .seq (.assign "w_z" (.lit 0)) (.while (.lt (V "w_z") (V "w_PR")) (zBody D))

/-- One clause `Y_y ∨ ¬Y_y`. -/
def tautBody : Com :=
  .seq (.write (.lit 2)) (.seq (.write (.mul (.lit 2) (V "w_y")))
    (.seq (.write (.add (.mul (.lit 2) (V "w_y")) (.lit 1))) (bump "w_y")))

/-- The loop over the variables. -/
def tautLoop : Com := .seq (.assign "w_y" (.lit 0)) (.while (.lt (V "w_y") (V "w_PS")) tautBody)

/-- **The formula and `k`.** -/
def mainCom (D : Data) : Com :=
  .seq boCom (.seq (LCom D) (.seq uCom (.seq (powCom "w_PR" D.r) (.seq (powCom "w_PS" D.s)
    (.seq (.write (.add (.mul (V "w_PR") (.lit D.cnf.length)) (V "w_PS")))
      (.seq (zLoop D) (.seq tautLoop (.write (V "w_k")))))))))

/-- The no-instance `1, 0, k`. -/
def noCom : Com := .seq (.write (.lit 1)) (.seq (.write (.lit 0)) (.write (V "w_k")))

/-- **The program.** -/
def prog (D : Data) : Com :=
  .seq Lax496464Proofs.WHierarchy.Machine.ReadTape.readTape
    (.seq headCom (.seq (fitCom D) (.ite (.eq (V "w_ft") (.lit 1)) (mainCom D) noCom)))

/-! ### The layout -/

/-- The scalars. -/
def scalars : List String :=
  ["rt_n", "rt_i", "rt_v", "w_sp", "w_N", "w_k", "w_ft", "w_p", "w_i", "w_t", "w_L", "w_e", "w_q",
    "w_f", "w_n", "w_PR", "w_PS", "w_w", "w_z", "w_bs", "w_cnt", "w_mt", "w_st", "w_c", "w_y"]

/-- The layout. -/
def layout : Layout := ⟨scalars, ["a", "bo", "U", "od"], 12⟩

theorem ok_seqList {L : Layout} : ∀ cs : List Com, (∀ c ∈ cs, Com.Ok L c) → Com.Ok L (seqList cs)
  | [], _ => by simp [seqList, Com.Ok]
  | c :: cs, h => ⟨h c (by simp), ok_seqList cs fun d hd => h d (by simp [hd])⟩

theorem ok_relCheck (p : ℕ × ℕ) : Com.Ok layout (relCheck p) := by
  simp [relCheck, layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr]

theorem ok_powSteps (v : String) (hv : v ∈ scalars) : ∀ e, Com.Ok layout (powSteps v e)
  | 0 => by simp [powSteps, Com.Ok]
  | e + 1 => ⟨ok_powSteps v hv e, by simpa [layout, scalars, Com.Ok, Expr.Ok] using hv⟩

theorem ok_decSteps : ∀ j c, Com.Ok layout (decSteps j c)
  | _, 0 => by simp [decSteps, Com.Ok]
  | j, c + 1 => by
    refine ⟨?_, ?_, ok_decSteps (j + 1) c⟩
    · simp [layout, scalars, Com.Ok, Expr.Ok]
    · simp [layout, scalars, Com.Ok, Expr.Ok]

theorem ok_matchCom (l : ℕ) : ∀ js q, Com.Ok layout (matchCom l js q)
  | [], _ => by simp [matchCom, Com.Ok]
  | j :: js, q => ⟨by simp [posE, elemE, layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
      ok_matchCom l js (q + 1)⟩

theorem ok_atomCom : ∀ a : Atom, Com.Ok layout (atomCom a)
  | .rel i js => by
    refine ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], by simp [layout, scalars, Com.Ok, Expr.Ok],
      by simp [layout, scalars, Com.Ok, Expr.Ok], by simp [layout, scalars, Com.Ok, Expr.Ok],
      by simp [layout, scalars, Cond.Ok, Expr.Ok, condExpr], ?_⟩
    exact ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], ok_matchCom _ _ _,
      by simp [layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
      by simp [layout, scalars, Com.Ok, Expr.Ok]⟩
  | .eq a b => by simp [atomCom, elemE, layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr]
  | .setVar _ => by simp [atomCom, Com.Ok]

theorem ok_codeCom : ∀ js, Com.Ok layout (codeCom js)
  | [] => by simp [codeCom, layout, scalars, Com.Ok, Expr.Ok]
  | j :: js => ⟨ok_codeCom js, by simp [layout, scalars, Com.Ok, Expr.Ok]⟩

theorem ok_clauseCom (C : List Lit) : Com.Ok layout (clauseCom C) := by
  refine ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], ok_seqList _ fun c hc => ?_,
    by simp [layout, scalars, Cond.Ok, Expr.Ok, condExpr],
    by simp [writeTaut0, layout, scalars, Com.Ok, Expr.Ok],
    by simp [layout, scalars, Com.Ok, Expr.Ok], ok_seqList _ fun c hc => ?_⟩
  · obtain ⟨l, -, rfl⟩ := List.mem_map.mp hc
    exact ⟨ok_atomCom _, by simp [layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr]⟩
  · obtain ⟨l, -, rfl⟩ := List.mem_map.mp hc
    exact ⟨ok_codeCom _, by simp [layout, scalars, Com.Ok, Expr.Ok]⟩

set_option maxHeartbeats 1000000 in
theorem ok_prog (D : Data) : Com.Ok layout (prog D) := by
  refine ⟨by simp [Lax496464Proofs.WHierarchy.Machine.ReadTape.readTape,
      Lax496464Proofs.WHierarchy.Machine.ReadTape.readLoop, Lax496464Proofs.WHierarchy.Machine.ReadTape.readBody,
      layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
    by simp [headCom, layout, scalars, Com.Ok, Expr.Ok],
    ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], ok_seqList _ fun c hc => ?_⟩,
    by simp [layout, scalars, Cond.Ok, Expr.Ok, condExpr], ?_,
    by simp [noCom, layout, scalars, Com.Ok, Expr.Ok]⟩
  · obtain ⟨p, -, rfl⟩ := List.mem_map.mp hc; exact ok_relCheck p
  · refine ⟨by simp [boCom, boLoop, boBody, layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
      by simp [LCom, layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
      by simp [uCom, fill1, fill1Body, fill2, fill2Body, pushNew, memScan, memLoop, memBody,
        layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
      ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], ok_powSteps _ (by simp [scalars]) _⟩,
      ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], ok_powSteps _ (by simp [scalars]) _⟩,
      by simp [layout, scalars, Com.Ok, Expr.Ok], ?_,
      by simp [tautLoop, tautBody, layout, scalars, Com.Ok, Cond.Ok, Expr.Ok, condExpr],
      by simp [layout, scalars, Com.Ok, Expr.Ok]⟩
    refine ⟨by simp [layout, scalars, Com.Ok, Expr.Ok],
      by simp [layout, scalars, Cond.Ok, Expr.Ok, condExpr],
      ⟨by simp [layout, scalars, Com.Ok, Expr.Ok], ok_decSteps 0 _⟩,
      ok_seqList _ fun c hc => ?_, by simp [layout, scalars, Com.Ok, Expr.Ok]⟩
    obtain ⟨C, -, rfl⟩ := List.mem_map.mp hc
    exact ok_clauseCom C

end Lax496464Proofs.WHierarchy.Lemmas.WDToWSat.ProgDefs
