name = "Lax496464"
defaultTargets = ["Lax496464"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

# the word RAM, and computation within an explicit instruction bound
[[require]]
name = "Lax808846"
git = "https://github.com/lax-archive/lax-submissions"
rev = "9394e531cc51cb67a0214bca3f9264dfe97ba5c7"
subDir = "word-ram/concepts"

# the classes P and NP
[[require]]
name = "Lax434930"
git = "https://github.com/EdouardBonnet/classical-complexity"
rev = "0c0840319318215fd7b36a9a822b81ce55cf6941"
subDir = "concepts"

# CNF formulas and their encoding, satisfiability, polynomial many-one reductions
[[require]]
name = "Lax429075"
git = "https://github.com/EdouardBonnet/cook-levin"
rev = "905f2da2698d5b38002676f74632aa716e731389"
subDir = "concepts"

[[lean_lib]]
name = "Lax496464"
